Repository openforests-git/apiato-core, pull requests merged in 2025-01, with the labels that each got.

#58 feat/MD/XL-9190 event generator
  src/Generator/Commands/EventGenerator.php
Labels: feature

#59 fix/MD/XL-10066 repository generator
  src/Generator/Commands/RepositoryGenerator.php
Labels: bug

#60 fix/MD/XL-10029 empty line at file start for migration file
  src/Generator/Commands/MigrationGenerator.php
Labels: bug

#61 fix/MD/XL-10008 remove preceding empty lines from generated routes
  src/Generator/Commands/RouteGenerator.php
Labels: bug

#62 deployment
  src/Generator/Commands/EventGenerator.php
  src/Generator/Commands/MigrationGenerator.php
  src/Generator/Commands/RepositoryGenerator.php
  src/Generator/Commands/RouteGenerator.php
Labels: deployment
